n1 = int(input("Digite um número"))
n2 = int(input("Digite um número"))
soma = (n1+n2)
print(f"A soma entre {n1} e {n2} é igual a: {soma}")
# Outro jeito: print("A soma entre {} e {} é igual a: {}".format(n1,n2,soma))