nome_c = str(input("Digite seu nome completo:")).strip()
print("Analisando seu nome...")
print(f"Seu nome em maiúsculo é {nome_c.upper()}")
print(f"Seu nome em minúsculo é {nome_c.lower()}")
print(f"Seu nome tem {len(nome_c) - nome_c.count(' ')} letras")
separa = nome_c.split()
print(f"Seu primeiro nome é {separa[0]} e tem {len(separa[0])} letras")