algo = input("Digite algo: ")
print("O tipo deste caracter é ", type(algo))
print("Só tem espaços?", algo.isspace())
print("É um número?", algo.isnumeric())
print("É alfabético?", algo.isalpha())
print("É um número?", algo.isalnum())
print("Está em minúsculo?", algo.islower())
print("Está em maiúsculo?", algo.isupper())
print("Está com maiúsculo e minúsculo?", algo.istitle())